[package]
name = "firmata-client-rs"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["Brandon Walsh <metasophiea@gmail.com>"]
readme = "README.md"
description = "A Firmata protocol client library."
edition = "2021"

[dependencies]
snafu = "0.8.4"
tracing = "0.1.40"

[dev-dependencies]
serialport = "4.5.1"
tracing-subscriber = "0.3.18"
